### Grocery Store Data Set
## This is a small data set consisting of 20 transactions.
This dataset contains 11 items : JAM, MAGGI, SUGAR, COFFEE, CHEESE, TEA, BOURNVITA, CORNFLAKES, BREAD, BISCUIT and MILK. <br>

Please find the top 5 rules sorted by confidence <br>
The Apriori Setting is: <br>
min_support = 0.002, min_confidence = 0.2, min_lift = 2, min_length = 2, max_length = 2

In [10]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [11]:
dataset = pd.read_csv('smallGroceryStore.csv', header = None, sep=',')
dataset

         0       1           2           3
0     MILK   BREAD     BISCUIT         NaN
1    BREAD    MILK     BISCUIT  CORNFLAKES
2    BREAD     TEA   BOURNVITA         NaN
3      JAM   MAGGI       BREAD        MILK
4    MAGGI     TEA     BISCUIT         NaN
5    BREAD     TEA   BOURNVITA         NaN
6    MAGGI     TEA  CORNFLAKES         NaN
7    MAGGI   BREAD         TEA     BISCUIT
8      JAM   MAGGI       BREAD         TEA
9    BREAD    MILK         NaN         NaN
10  COFFEE    COCK     BISCUIT  CORNFLAKES
11  COFFEE    COCK     BISCUIT  CORNFLAKES
12  COFFEE   SUGER   BOURNVITA         NaN
13   BREAD  COFFEE        COCK         NaN
14   BREAD   SUGER     BISCUIT         NaN
15  COFFEE   SUGER  CORNFLAKES         NaN
16   BREAD   SUGER   BOURNVITA         NaN
17   BREAD  COFFEE       SUGER         NaN
18   BREAD  COFFEE       SUGER         NaN
19     TEA    MILK      COFFEE  CORNFLAKES